spring.application.name=nishiki_koi_shop

#spring.datasource.url=jdbc:postgresql://localhost:5432/nishiki_koi_shop
#.datasource.url=jdbc:postgresql://localhost:5435/nishiki_koi_shop
spring.datasource.username=postgres
spring.datasource.password=12345
#spring.datasource.password=lam1782004
#spring.datasource.password=123456
#spring.jpa.hibernate.ddl-auto= create-drop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.driver-class-name=org.postgresql.Driver

